application: appname
version: 1
runtime: go
api_version: go1

env_variables:
    ALLOWED_ORIGINS: "http://dev.my_app.com:3000"

handlers:
# all static files
- url: /static
  static_dir: ../static

# index.html for /
- url: /
  static_files: ../index.html
  upload: ../index.html

- url: /.*
  script: _go_app